spring:
  rabbitmq:
    host: dev.rabbitmq.i.sixi.com       #rabbitmq�����ַ
    port: 5672              #rabbitmqͨ�Ŷ˿�
    username: root    #rabbitmq�û���
    password: root     #rabbitmq����

rocketmq:
  name-server: 192.168.2.123:9876
  producer:
    group: xxb-group
# ֪ͨtopic��tag����
contract-customer:
  consumerGroup: xxb
  topic: topic_xxb_customer_test
contract-producer:
  topic: topic_xxb_producer_test
server:
  port: 8882

